<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-EJE643E" failures="1" tests="3" name="Tests1" time="5.345" errors="0" timestamp="2024-04-28T12:33:05 CDT" skipped="0">
  <testcase classname="Tests1" name="doLogin3" time="1.865"/>
  <testcase classname="Tests1" name="doLogin1" time="1.844">
    <failure message="The following asserts failed:
	expected [16] but found [15]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [16] but found [15]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at Tests1.doLogin1(Tests1.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
    <system-out>
      <![CDATA[<a href="E:\NewProject\screenshot.jpg" target="_blank">Screenshot link
<br>
<a href="E:\NewProject\screenshot.jpg" target="_blank"><img height=150 width=150 src="E:\NewProject\screenshot.jpg">]]>
    </system-out>
  </testcase> <!-- doLogin1 -->
  <testcase classname="Tests1" name="doLogin2" time="1.636">
    <system-out>
      <![CDATA[<a href="E:\NewProject\screenshot.jpg" target="_blank">Screenshot link
<br>
<a href="E:\NewProject\screenshot.jpg" target="_blank"><img height=150 width=150 src="E:\NewProject\screenshot.jpg">]]>
    </system-out>
  </testcase> <!-- doLogin2 -->
  <system-out>
    <![CDATA[<a href="E:\NewProject\screenshot.jpg" target="_blank">Screenshot link
<br>
<a href="E:\NewProject\screenshot.jpg" target="_blank"><img height=150 width=150 src="E:\NewProject\screenshot.jpg">
<a href="E:\NewProject\screenshot.jpg" target="_blank">Screenshot link
<br>
<a href="E:\NewProject\screenshot.jpg" target="_blank"><img height=150 width=150 src="E:\NewProject\screenshot.jpg">]]>
  </system-out>
</testsuite> <!-- Tests1 -->
